upgrade Multibrot with new archive mechanism

diff --git a/.github/workflows/tweet_multibrot3.yml b/.github/workflows/tweet_multibrot3.yml
--- a/.github/workflows/tweet_multibrot3.yml
+++ b/.github/workflows/tweet_multibrot3.yml
@@ -1,17 +1,12 @@
 name: tweet_multibrot3 (Hourly fractals)
 
 on:
-  # schedule:
-  #   - cron: '15 */3 * * *'
-
+  schedule:
+    - cron: '0 */2 * * *'
   workflow_dispatch:
 
-  # Testing purposes
-  # push:
-  #   branches:
-  #     - main
-
 env:
+  FRACTAL_NAME: Multibrot3
   # This one should mirror the one in utils/constants.py and .gitignore
   VENV_CACHE_DIR_NAME: THE_VENV_CACHE
 
@@ -21,7 +16,7 @@ jobs:
     permissions:
       contents: write
     steps:
-      - name: Checkout
+      - name: Checkout main branch
         uses: actions/checkout@v3
       
       - name: Try to restore the VENV cache
@@ -35,13 +30,7 @@ jobs:
         if: steps.restore-cache.outputs.cache-hit != 'true'
         run: exit 1
 
-      - name: Generate image
-        run: |
-          source $GITHUB_WORKSPACE/$VENV_CACHE_DIR_NAME/bin/activate
-          python tweet_multibrot3/generate
-
       - name: Tweet!
-        id: tweet
         env:
           TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY_2 }}
           TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY_2 }}
@@ -49,22 +38,29 @@ jobs:
           TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET_2 }}
         run: |
           source $GITHUB_WORKSPACE/$VENV_CACHE_DIR_NAME/bin/activate
-          python tweet_multibrot3/do_tweet.py
+          python tweet_multibrot3
+
+      - name: Checkout metadata branch
+        uses: actions/checkout@v3
+        with:
+          ref: fractal-metadata
 
       - name: Archiving
-        env:
-          TWEET_ID: ${{ steps.tweet.outputs.tweet_id }}
         run: |
-          chmod +x tweet_multibrot3/do_archive.sh
-          tweet_multibrot3/do_archive.sh
+          python archive_manager.py
 
-          echo "::group::Debug"
-          git log
-          echo "::endgroup::"
-
-          # Commit
-          git config user.name "tweet_multibrot3"
+          git config user.name "$FRACTAL_NAME"
           git config user.email "${{ vars.GIT_EMAIL }}"
           git add .
-          git commit -m "Archived — $(date +'%Y %b %e, %l:%M %p')"
+          git commit -m "$FRACTAL_NAME — $(date +'%Y %b %e, %l:%M %p')"
+          
+          echo "INFO: Attempt the first git push"
           git push
+
+          # Just in case there are multiple workflows pushing at nearly the same time
+          if [ $? -ne 0 ]; then
+            # Repush if the first pull failed
+            echo "INFO: Attempt the second git push"
+            git pull
+            git push
+          fi
