this is a dev commit: 10 files changed, 190 insertions(+), 131 deletions(-)
 .../{xworkflowsx => workflows}/make-venv-cache.yml |   0

 .../tweet_burning_ship.yml                         |  41 ++++---

 .../tweet_mandelbrot.yml                           |   4 +-

 .../tweet_multibrot3.yml                           |   4 +-

 .../{xworkflowsx => workflows}/tweet_newton.yml    |   4 +-

 core/fractal_burning_ship.py                       |  78 +++++--------

 core/post_online.py                                |   4 +-

 core/render_img.py (new)                           | 128 +++++++++++++++++++++

 core/save_img.py (gone)                            |  56 ---------

 core/shared.py                                     |   2 +

message generated by QWD (github.com/nvfp/qwd)

diff --git a/.github/workflows/tweet_burning_ship.yml b/.github/workflows/tweet_burning_ship.yml
--- a/.github/workflows/tweet_burning_ship.yml
+++ b/.github/workflows/tweet_burning_ship.yml
@@ -1,9 +1,12 @@
 name: Burning ship
 
 on:
-  schedule:
-    - cron: '0 */2 * * *'
+  # schedule:
+  #   - cron: '0 */2 * * *'
   workflow_dispatch:
+  pull_requests:
+    # - opened
+    - synchronize
 
 env:  # Note: changing these values will require changes in other parts of the code, so it's better to avoid it if possible.
   FRACTAL_NAME: BurningShip
@@ -36,23 +39,23 @@ jobs:
           X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
           MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
 
-      - uses: actions/checkout@v4  # switch to metadata branch
-        with:
-          ref: fractal_metadata_20240226
+      # - uses: actions/checkout@v4  # switch to metadata branch
+      #   with:
+      #     ref: fractal_metadata_20240226
 
-      - run: |  # save the metadata file
-          python save_the_md_file.py
+      # - run: |  # save the metadata file
+      #     python save_the_md_file.py
 
-          git config user.name "$FRACTAL_NAME"
-          git config user.email "${{ vars.GIT_EMAIL }}"
-          git add .
-          git commit -m "$FRACTAL_NAME — $(date +'%Y %b %e, %l:%M %p')"
+      #     git config user.name "$FRACTAL_NAME"
+      #     git config user.email "${{ vars.GIT_EMAIL }}"
+      #     git add .
+      #     git commit -m "$FRACTAL_NAME — $(date +'%Y %b %e, %l:%M %p')"
           
-          echo "INFO: Attempt the first git push"
-          git push
+      #     echo "INFO: Attempt the first git push"
+      #     git push
 
-          if [ $? -ne 0 ]; then  # Rerun if the first pull fails, just in case there are multiple workflows pushing at nearly the same time.
-            echo "INFO: Attempt the second git push"
-            git pull
-            git push
-          fi
+      #     if [ $? -ne 0 ]; then  # Rerun if the first pull fails, just in case there are multiple workflows pushing at nearly the same time.
+      #       echo "INFO: Attempt the second git push"
+      #       git pull
+      #       git push
+      #     fi
